#
# Top-level makefile for the 'LLVM-Project'.
#
DO_MAKE = $(MAKE) -f Makefile.Windows

DIRS = $(addprefix llvm/,  lib tools utils unittests) \
       $(addprefix clang/, lib tools utils unittests)

default: all

all clean vclean depend:
	for d in $(DIRS) ; do        \
		$(DO_MAKE) -C $$d $@   ; \
		if [ $$? -ne 0 ]; then   \
			echo "make failed" ; \
			exit 1 ;             \
		fi ;                     \
	done
	@echo "Done $@."
