#
# GNU Makefile for 'clang/tools/c-index-test'.
#
TOP_DIR = ../../..
TARGETS = $(BUILD_DIR)/bin/c-index-test.exe

include $(TOP_DIR)/Common.Windows

C_SRC       = c-index-test.c
CPP_SRC     = core_main.cpp
ALL_SOURCES = $(C_SRC) $(CPP_SRC)

OBJECTS = $(call c_to_obj,   $(C_SRC)) \
          $(call cpp_to_obj, $(CPP_SRC))

all: $(GENERATED) $(TARGETS)

LIBS = $(addprefix $(BUILD_DIR)/lib/, \
         clangAST.lib                 \
         clangAnalysis.lib            \
         clangBasic.lib               \
         clangCodeGen.lib             \
         clangDriver.lib              \
         clangEdit.lib                \
         clangFrontend.lib            \
         clangIndex.lib               \
         clangLex.lib                 \
         clangParse.lib               \
         clangSema.lib                \
         clangSerialization.lib       \
         libclang.lib)

LIBS += $(addprefix $(BUILD_DIR)/lib/,  \
          LLVMAggressiveInstCombine.lib \
          LLVMAnalysis.lib              \
          LLVMAsmParser.lib             \
          LLVMBinaryFormat.lib          \
          LLVMBitstreamReader.lib       \
          LLVMBitReader.lib             \
          LLVMBitWriter.lib             \
          LLVMCore.lib                  \
          LLVMCoroutines.lib            \
          LLVMCoverage.lib              \
          LLVMDemangle.lib              \
          LLVMFrontendOpenMP.lib        \
          LLVMInstCombine.lib           \
          LLVMInstrumentation.lib       \
          LLVMIpo.lib                   \
          LLVMIRReader.lib              \
          LLVMLinker.lib                \
          LLVMLTO.lib                   \
          LLVMMC.lib                    \
          LLVMMCParser.lib              \
          LLVMObjCARCOpts.lib           \
          LLVMObject.lib                \
          LLVMOption.lib                \
          LLVMPasses.lib                \
          LLVMProfileData.lib           \
          LLVMRemarks.lib               \
          LLVMScalarOpts.lib            \
          LLVMSupport.lib               \
          LLVMTarget.lib                \
          LLVMTextAPI.lib               \
          LLVMTransformUtils.lib        \
          LLVMVectorize.lib)

#
# External libraries needed:
#
EX_LIBS = advapi32.lib ole32.lib shell32.lib version.lib

ifeq ($(USE_ZLIB),1)
  CFLAGS  += -I$(ZLIB_ROOT)
  EX_LIBS += $(ZLIB_LIB)
endif

ifeq ($(USE_XML2),1)
  CFLAGS += -I$(XML2_ROOT)/include

  #
  # In case 'libxml2' was configured with 'LIBXML_ICONV_ENABLED'
  #
  CFLAGS += -I$(ICONV_ROOT)/include

  #
  # Use the static 'xml2.lib'
  #
  CFLAGS += -DLIBXML_STATIC

  EX_LIBS += $(XML2_LIB) $(LZMA_LIB) $(ICONV_LIB) ws2_32.lib
endif

$(BUILD_DIR)/bin/c-index-test.exe: $(OBJECTS) $(LIBS) $(OBJ_DIR)/c-index-test.res
	$(call link_EXE, $@, $^ $(EX_LIBS))

$(OBJ_DIR)/c-index-test.rc: $(MDEPEND)
	$(call make_rc, $@, c-index-test.exe, VFT_APP, Clang test-tool.)

-include .depend.Windows

