#
# Top-level makefile for 'llvm/unittests'.
#
TOP_DIR = ../..

include $(TOP_DIR)/Common.Windows

all depend clean vclean:
	$(call do_make, ADT,          $@)
	$(call do_make, AsmParser,    $@)
	$(call do_make, BinaryFormat, $@)
	$(call do_make, Support,      $@)
