#
# GNU Makefile for 'llvm/lib/IRReader'.
#
TOP_DIR = ../../..
TARGETS = $(BUILD_DIR)/lib/LLVMIRReader.lib

include $(TOP_DIR)/Common.Windows

LIB_SRC = IRReader.cpp

ALL_SOURCES = $(LIB_SRC)

LIB_OBJ = $(call cpp_to_obj, $(LIB_SRC))

all: $(GENERATED) $(TARGETS)

$(BUILD_DIR)/lib/LLVMIRReader.lib: $(LIB_OBJ)
	 $(call create_lib, $@, $^)

-include .depend.Windows

